### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by joergplewe** [Microsoft/PowerBI-visuals-sampleBarChart#14]
I cannot compile and run the sample as I plainly cloned the repo.

Almost the same things happens when I use d3.js in other projects. 
Help is urgently needed!

```
C:\dev\MR\pbiviz\PowerBI-visuals-sampleBarChart>pbiviz start
 info   Building visual...
 error  UNKNOWN RangeError: Maximum call stack size exceeded
    at isMatchingReference (C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:32599:37)
    at narrowTypeByTypeof (C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:33453:22)
    at narrowTypeByBinaryExpression (C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:33389:36)
    at narrowType (C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:33616:32)
    at getTypeAtFlowCondition (C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:33232:36)
    at getTypeAtFlowNode (C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:33113:32)
    at getTypeAtFlowBranchLabel (C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:33258:36)
    at getTypeAtFlowNode (C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:33124:29)
    at getTypeAtFlowCondition (C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:33218:32)
    at getTypeAtFlowNode (C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:33113:32)
```

**Comment by joergplewe** [comment]
Found one solution:

Upgrade tsc compiler version used by powerbi-visual-tools from 2.1.5 to 2.2.1.

Reason: tsc 2.1.5 does not let pass d3.js which needs to be added to tsconfig.json. 2.2.1 does.

**Comment by murilowlima** [comment]
I updated tsc to 2.2.1 but this issue still occurs.

**Comment by joergplewe** [comment]
Are you sure you updated the compiler version that `pbiviz` uses (for me an Windows: `C:\Users\Jörg\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js`)? It does not use the one globally installed by npm.

**Comment by joergplewe** [comment]
Another workaround is to remove reference to d3.js from trconfig.json and place it to pbiviz.json in section `externalJS`.

**Comment by joergplewe** [comment]
see also https://github.com/Microsoft/PowerBI-visuals/issues/136

**Comment by AviSander** [comment]
thx for the input. fixed in https://github.com/Microsoft/PowerBI-visuals-sampleBarChart/pull/18/commits
