### ISSUE TITLE
Package still error

### ISSUE THREAD

**Issue by reinhardtyang** [Microsoft/PowerBI-visuals-sampleBarChart#30]
After NPM install, the original error changes to following:
C:\Users\reyang\PBI\barchart>pbiviz package
 info   Building visual...
 error  UNKNOWN { Error: ENOENT: no such file or directory, open 'C:\Users\reyang\PBI\barchart\node_modules\d3\d3.min.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at files.map.file (C:\Users\reyang\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:207:26)
    at Array.map (<anonymous>)
    at Promise (C:\Users\reyang\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:204:33)
    at new Promise (<anonymous>)
    at concatExternalJS (C:\Users\reyang\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:196:12)
    at compileTypescript.then (C:\Users\reyang\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:261:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\reyang\\PBI\\barchart\\node_modules\\d3\\d3.min.js' }

How to fix this?

**Comment by uve** [comment]
Duplicated #29
